import { ArrowRight, Check, ChevronRight } from "lucide-react";
import { Link, Navigate, useParams } from "react-router-dom";
import PageLayout from "@/components/layout/PageLayout";
import SEO from "@/components/SEO";
import ScrollReveal from "@/components/shared/ScrollReveal";
import { Button } from "@/components/ui/button";
import { getIndustry, legacyIndustryRedirects } from "@/data/industries";
import { getServicePrice } from "@/data/pricingData";
import { portfolioProjects } from "@/data/portfolioData";
import { buildBreadcrumbSchema } from "@/lib/seoSchema";

const IndustryDetailPage = () => {
  const { slug = "" } = useParams();
  if (legacyIndustryRedirects[slug]) return <Navigate to={`/industries/${legacyIndustryRedirects[slug]}`} replace />;
  const industry = getIndustry(slug);
  if (!industry) return <Navigate to="/industries" replace />;
  const relevantWork = portfolioProjects.filter((project) => industry.featuredProjectSlugs.includes(project.slug));
  const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: industry.faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) };

  return <PageLayout>
    <SEO path={`/industries/${industry.slug}`} title={industry.seoTitle} description={industry.seoDescription} jsonLd={[buildBreadcrumbSchema([{ name: "Industries", path: "/industries" }, { name: industry.name, path: `/industries/${industry.slug}` }]), faqSchema]} />
    <section className="relative overflow-hidden bg-primary px-4 pb-20 pt-32 text-primary-foreground sm:px-6 sm:pb-28 sm:pt-40"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_20%,hsl(var(--accent)/.25),transparent_36%)]" /><div className="container-wide relative mx-auto"><nav aria-label="Breadcrumb" className="flex items-center gap-2 text-xs uppercase tracking-[.18em] text-primary-foreground/45"><Link to="/industries" className="hover:text-accent">Industries</Link><ChevronRight className="h-3 w-3" /><span>{industry.name}</span></nav><p className="mt-12 text-xs font-bold uppercase tracking-[.24em] text-accent">{industry.eyebrow}</p><h1 className="mt-6 max-w-6xl text-5xl leading-[.96] sm:text-7xl lg:text-8xl">{industry.heroTitle}</h1><div className="mt-10 grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><p className="max-w-2xl text-lg leading-relaxed text-primary-foreground/60">{industry.summary}</p><div className="flex flex-wrap gap-3"><Link to="/contact"><Button variant="accent" size="lg">Get a Quote <ArrowRight className="ml-2 h-4 w-4" /></Button></Link><Link to="/work"><Button variant="dark-outline" size="lg">View Our Work</Button></Link></div></div></div></section>
    <section className="section-padding bg-background"><div className="container-wide mx-auto grid gap-12 lg:grid-cols-[.75fr_1.25fr] lg:gap-24"><ScrollReveal><div className="lg:sticky lg:top-32"><p className="text-xs font-bold uppercase tracking-[.22em] text-accent">Why digital presence matters</p><h2 className="mt-5 text-3xl sm:text-5xl">Trust begins before the first conversation.</h2></div></ScrollReveal><ScrollReveal delay={.08}><p className="text-xl leading-relaxed text-muted-foreground">{industry.whyItMatters}</p></ScrollReveal></div></section>
    <section className="border-y border-border bg-card section-padding"><div className="container-wide mx-auto grid gap-14 lg:grid-cols-2 lg:gap-24"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-accent">Common friction</p><h2 className="mt-4 text-3xl sm:text-5xl">Where businesses lose momentum</h2><div className="mt-8 divide-y divide-border border-y border-border">{industry.challenges.map((challenge, index) => <div key={challenge} className="grid grid-cols-[3rem_1fr] py-5"><span className="text-xs text-accent">0{index + 1}</span><p>{challenge}</p></div>)}</div></div><div><p className="text-xs font-bold uppercase tracking-[.22em] text-accent">What improves</p><h2 className="mt-4 text-3xl sm:text-5xl">A clearer digital operating position</h2><div className="mt-8 space-y-3">{industry.outcomes.map((outcome) => <div key={outcome} className="flex items-center gap-3 rounded-xl border border-border bg-background p-5"><Check className="h-4 w-4 shrink-0 text-accent" />{outcome}</div>)}</div></div></div></section>
    <section className="section-padding bg-background"><div className="container-wide mx-auto"><p className="text-xs font-bold uppercase tracking-[.22em] text-accent">Recommended solutions</p><h2 className="mt-4 max-w-3xl text-3xl sm:text-5xl">A service mix shaped around {industry.name.toLowerCase()}</h2><div className="mt-12 divide-y divide-border border-y border-border">{industry.solutions.map((solution, index) => <Link key={solution.title} to={`/services/${solution.serviceSlug}`} className="group grid gap-4 py-7 sm:grid-cols-[4rem_1fr_200px_auto] sm:items-center sm:px-4"><span className="text-xs text-accent">0{index + 1}</span><div><h3 className="text-xl group-hover:text-accent">{solution.title}</h3><p className="mt-2 max-w-2xl text-sm leading-relaxed text-muted-foreground">{solution.description}</p></div><span className="text-sm text-foreground/55">{getServicePrice(solution.serviceSlug)?.amount ?? "Custom Quote"}</span><ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></Link>)}</div></div></section>
    <section className="border-y border-border bg-primary section-padding text-primary-foreground"><div className="container-wide mx-auto grid gap-12 lg:grid-cols-[.75fr_1.25fr] lg:gap-24"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-accent">Industry considerations</p><h2 className="mt-4 text-3xl sm:text-5xl">Details that shape the right solution</h2></div><div className="divide-y divide-white/10 border-y border-white/10">{industry.considerations.map((item, index) => <div key={item} className="grid grid-cols-[3rem_1fr] py-6"><span className="text-xs text-accent">0{index + 1}</span><p className="text-primary-foreground/70">{item}</p></div>)}</div></div></section>
    {relevantWork.length > 0 && <section className="section-padding bg-background"><div className="container-wide mx-auto"><p className="text-xs font-bold uppercase tracking-[.22em] text-accent">Relevant Creative Emman work</p><h2 className="mt-4 text-3xl sm:text-5xl">Related experience and thinking</h2><div className="mt-12 grid gap-6 md:grid-cols-3">{relevantWork.map((project) => <Link key={project.slug} to={`/work/${project.category}/${project.slug}`} className="group overflow-hidden rounded-2xl border border-border bg-card"><div className="aspect-[4/3] overflow-hidden"><img src={project.coverImage} alt="" loading="lazy" className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-[1.03]" /></div><div className="p-6"><p className="text-xs uppercase tracking-wider text-accent">{project.status}</p><h3 className="mt-3 text-xl group-hover:text-accent">{project.title}</h3></div></Link>)}</div></div></section>}
    <section className="border-t border-border bg-card section-padding"><div className="container-narrow mx-auto"><p className="text-xs font-bold uppercase tracking-[.22em] text-accent">Frequently asked questions</p><div className="mt-8 divide-y divide-border border-y border-border">{industry.faqs.map((faq) => <div key={faq.question} className="grid gap-4 py-7 md:grid-cols-[.85fr_1.15fr] md:gap-12"><h3 className="text-lg">{faq.question}</h3><p className="text-sm leading-relaxed text-muted-foreground">{faq.answer}</p></div>)}</div></div></section>
    <section className="bg-primary px-4 py-24 text-center text-primary-foreground"><div className="container-narrow mx-auto"><h2 className="text-4xl sm:text-6xl">Build a stronger {industry.name.toLowerCase()} presence.</h2><p className="mx-auto mt-5 max-w-xl text-primary-foreground/55">Share the current challenge and the outcome you need. We’ll define a sensible starting point.</p><Link to="/contact" className="mt-8 inline-block"><Button variant="accent" size="lg">Get a Quote <ArrowRight className="ml-2 h-4 w-4" /></Button></Link></div></section>
  </PageLayout>;
};

export default IndustryDetailPage;
