import { ArrowRight, CheckCircle2 } from "lucide-react";
import { Link } from "react-router-dom";
import PageLayout from "@/components/layout/PageLayout";
import SEO from "@/components/SEO";
import ScrollReveal from "@/components/shared/ScrollReveal";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { buildBreadcrumbSchema } from "@/lib/seoSchema";

const tracks = ["Web Development", "Frontend Development", "UI/UX Design", "Graphic & Brand Design", "Social Media Management", "Photography", "Videography", "Video Editing", "Motion Graphics", "Business Development"];
const steps = ["Review the programme and choose the most relevant discipline", "Submit the internship application with accurate information", "Complete any requested screening task or conversation", "Receive a decision and cohort details if selected"];

const Internships = () => <PageLayout>
  <SEO path="/internships" title="Creative & Technology Internships | Creative Emman Limited" description="Explore applied internship tracks in web development, design, media, marketing and business development with Creative Emman Limited." jsonLd={buildBreadcrumbSchema([{ name: "Internships", path: "/internships" }])} />
  <section className="relative overflow-hidden bg-primary px-4 pb-20 pt-32 text-primary-foreground sm:px-6 sm:pb-28 sm:pt-40"><div className="absolute inset-0 bg-[radial-gradient(circle_at_78%_20%,hsl(var(--accent)/.25),transparent_36%)]" /><div className="container-wide relative mx-auto"><p className="text-xs font-bold uppercase tracking-[.24em] text-accent">Internships</p><h1 className="mt-6 max-w-6xl text-5xl leading-[.96] sm:text-7xl lg:text-8xl">Learn by doing work that demands thought, craft and responsibility.</h1><p className="mt-8 max-w-2xl text-lg leading-relaxed text-primary-foreground/60">Creative Emman Limited internships are applied learning experiences for emerging practitioners who want structured feedback, practical exposure and a clearer view of professional delivery.</p><Link to="/applications" className="mt-9 inline-block"><Button variant="accent" size="lg">Apply for an Internship <ArrowRight className="ml-2 h-4 w-4" /></Button></Link></div></section>
  <section className="section-padding bg-background"><div className="container-wide mx-auto grid gap-12 lg:grid-cols-[.72fr_1.28fr] lg:gap-24"><ScrollReveal><div><p className="text-xs font-bold uppercase tracking-[.22em] text-accent">Who it is for</p><h2 className="mt-5 text-3xl sm:text-5xl">Curious people ready to practise consistently.</h2><p className="mt-5 leading-relaxed text-muted-foreground">Applicants should be prepared to learn, communicate, receive critique and complete assigned work. Prior experience helps, but evidence of commitment and thoughtful effort matters too.</p></div></ScrollReveal><div><p className="text-xs font-bold uppercase tracking-[.22em] text-accent">Available disciplines</p><div className="mt-5 grid gap-px overflow-hidden rounded-2xl border border-border bg-border sm:grid-cols-2">{tracks.map((track) => <div key={track} className="flex min-h-16 items-center gap-3 bg-card p-5"><CheckCircle2 className="h-4 w-4 shrink-0 text-accent" /><span>{track}</span></div>)}</div></div></div></section>
  <section className="border-y border-border bg-card section-padding"><div className="container-wide mx-auto grid gap-12 lg:grid-cols-2 lg:gap-24"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-accent">Learning structure</p><h2 className="mt-5 text-3xl sm:text-5xl">Direction, practice, review and reflection.</h2><p className="mt-5 leading-relaxed text-muted-foreground">The exact structure depends on the discipline and current cohort. Where available, interns work through guided tasks, observe real delivery practices and improve work through feedback.</p></div><div><p className="text-xs font-bold uppercase tracking-[.22em] text-accent">What interns can gain</p><ul className="mt-6 space-y-4 text-foreground/75">{["A clearer professional workflow", "Practice translating briefs into deliverables", "Constructive critique and review habits", "A better understanding of multidisciplinary collaboration", "Portfolio-ready learning outcomes where appropriate"].map((item) => <li key={item} className="flex gap-3"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-accent" />{item}</li>)}</ul><p className="mt-6 text-sm text-muted-foreground">Participation does not guarantee employment, paid client work or a permanent role.</p></div></div></section>
  <section className="section-padding bg-background"><div className="container-wide mx-auto"><p className="text-xs font-bold uppercase tracking-[.22em] text-accent">Application process</p><div className="mt-8 divide-y divide-border border-y border-border">{steps.map((step, index) => <div key={step} className="grid grid-cols-[4rem_1fr] py-6"><span className="text-xs text-accent">0{index + 1}</span><p className="text-lg">{step}</p></div>)}</div></div></section>
  <section className="border-t border-border bg-card section-padding"><div className="container-narrow mx-auto"><p className="text-xs font-bold uppercase tracking-[.22em] text-accent">Questions</p><Accordion type="single" collapsible className="mt-5"><AccordionItem value="one"><AccordionTrigger>Are internships always open?</AccordionTrigger><AccordionContent>Availability depends on team capacity and current cohorts. The application page shows the route for submitting interest when opportunities are available.</AccordionContent></AccordionItem><AccordionItem value="two"><AccordionTrigger>Is prior experience required?</AccordionTrigger><AccordionContent>Requirements vary by discipline. Relevant samples, personal projects and evidence of consistent learning can help demonstrate readiness.</AccordionContent></AccordionItem><AccordionItem value="three"><AccordionTrigger>Does an internship guarantee employment?</AccordionTrigger><AccordionContent>No. Internship participation is an educational and practical experience and does not guarantee a job offer.</AccordionContent></AccordionItem></Accordion></div></section>
  <section className="bg-primary px-4 py-24 text-center text-primary-foreground"><div className="container-narrow mx-auto"><h2 className="text-4xl sm:text-6xl">Ready to apply?</h2><p className="mx-auto mt-5 max-w-xl text-primary-foreground/55">Choose internship on the applications page and tell us which discipline best matches your learning goals.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Link to="/applications"><Button variant="accent" size="lg">Open Applications <ArrowRight className="ml-2 h-4 w-4" /></Button></Link><Link to="/trainings"><Button variant="dark-outline" size="lg">Explore Trainings</Button></Link></div></div></section>
</PageLayout>;

export default Internships;
